@root = http://localhost:5603/todos
@item-update = 5ca93e60-c3ad-409f-9336-9bef738e74bf
@item-delete = a003f6ab-fb91-43ed-8a4d-5d44910c5863

### get all todo items
GET {{root}}

### create an todo item
POST {{root}}
Content-Type: application/json

{
    "title": "todo 2",
    "completed": false
}

### update an todo item
PUT {{root}}/{{item-update}}
Content-Type: application/json

{
    "title": "test update todo item",
    "completed": true
}

### delete an todo item
DELETE {{root}}/{{item-delete}}